<?php

namespace NAO\BirdsBundle\Repository;

/**
 * VisualBirdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisualBirdRepository extends \Doctrine\ORM\EntityRepository
{
}
